// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/app/Header.vue')['default']
    AppHeahder: typeof import('./src/components/app/Heahder.vue')['default']
    AuthLoginForm: typeof import('./src/components/auth/LoginForm.vue')['default']
    QueryLoader: typeof import('./src/components/QueryLoader/index.vue')['default']
    QueryLoaderBase: typeof import('./src/components/QueryLoader/base.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiButtonBase: typeof import('./src/components/ui/button/Base.vue')['default']
    UiButtonFull: typeof import('./src/components/ui/button/Full.vue')['default']
    UiFormControl: typeof import('./src/components/ui/form/Control.vue')['default']
    UiFormError: typeof import('./src/components/ui/form/Error.vue')['default']
    UiPasswordInput: typeof import('./src/components/ui/PasswordInput.vue')['default']
    UiTextInput: typeof import('./src/components/ui/TextInput.vue')['default']
    UserSignupForm: typeof import('./src/components/user/SignupForm.vue')['default']
  }
}
