// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppAppFooter: typeof import('./src/components/app/AppFooter.vue')['default']
    AppFooter: typeof import('./src/components/app/Footer.vue')['default']
    AppHeader: typeof import('./src/components/app/Header.vue')['default']
    AppPageTitle: typeof import('./src/components/app/PageTitle.vue')['default']
    AuthLoginForm: typeof import('./src/components/auth/LoginForm.vue')['default']
    QueryLoader: typeof import('./src/components/QueryLoader/index.vue')['default']
    QueryLoaderBase: typeof import('./src/components/QueryLoader/base.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiButtonBase: typeof import('./src/components/ui/button/Base.vue')['default']
    UiButtonCta: typeof import('./src/components/ui/button/Cta.vue')['default']
    UiButtonFull: typeof import('./src/components/ui/button/Full.vue')['default']
    UiButtonIcon: typeof import('./src/components/ui/button/Icon.vue')['default']
    UiButtonLink: typeof import('./src/components/ui/button/Link.vue')['default']
    UiCenter: typeof import('./src/components/ui/Center.vue')['default']
    UiCheckbox: typeof import('./src/components/ui/Checkbox.vue')['default']
    UiContainer: typeof import('./src/components/ui/Container.vue')['default']
    UiForm: typeof import('./src/components/ui/form/index.vue')['default']
    UiFormControl: typeof import('./src/components/ui/form/Control.vue')['default']
    UiFormError: typeof import('./src/components/ui/form/Error.vue')['default']
    UiFormFooter: typeof import('./src/components/ui/form/Footer.vue')['default']
    UiPasswordInput: typeof import('./src/components/ui/PasswordInput.vue')['default']
    UiSpinner: typeof import('./src/components/ui/Spinner.vue')['default']
    UiSurface: typeof import('./src/components/ui/Surface.vue')['default']
    UiTextInput: typeof import('./src/components/ui/TextInput.vue')['default']
    UserLostPasswordForm: typeof import('./src/components/user/LostPasswordForm.vue')['default']
    UserResetPasswordForm: typeof import('./src/components/user/ResetPasswordForm.vue')['default']
    UserSignupForm: typeof import('./src/components/user/SignupForm.vue')['default']
  }
}
